### PR TITLE
Make xarray an optional dependency

### PR DESCRIPTION
**Pull request by tomwhite**

### CODE REVIEW

**Review by TomNicholas — COMMENTED** [review]
Code-wise this looks good, and was the same change I had imagined.

We should really test the no-xarray case in CI though - that should also improve the CodeCov score.

**Comment by tomwhite** [comment]
> We should really test the no-xarray case in CI though - that should also improve the CodeCov score.

The no xarray case is being tested in `min-dependencies` (https://github.com/pangeo-data/rechunker/blob/master/.github/workflows/ci.yaml#L29-L43). But it's less than it was as `test_rechunk.py` is now skipped.

We could perhaps split `test_rechunk.py` into xarray and non-xarray files to make it easier to skip the xarray part for `min-dependencies`.

**Comment by tomwhite** [comment]
Splitting `test_rechunk.py` seems to be a bit harder than I thought as there are fixtures used by xarray and non-xarray tests, so rather than duplicate them, I have just been a bit more selective about skipping the xarray tests.

**Review by rabernat — APPROVED** [review]
This is fine with me! 👍

**Comment by tomwhite** [comment]
i'd like to merge this soon unless there are any more comments.

**Comment by tomwhite** [comment]
Thanks @rabernat!

**Pull request merged**
