### PR TITLE
Release procedure.

### PR DESCRIPTION
**Pull request by TomAugspurger**

### CODE REVIEW

**Comment by rabernat** [comment]
Should we consider making a github action to automate release on a new tag?

**Comment by rabernat** [comment]
Can this be resolved / merged? I'd like to do a rechunker release, since we have so many new features.

**Comment by TomAugspurger** [comment]
Let me fix the merge conflict quick.

**Comment by TomAugspurger** [comment]
OK, should be set here. The manual steps to releasing are at https://github.com/pangeo-data/rechunker/pull/44/files#diff-e052d37005ef738791e533f325afeb1f194d5d2c18e5cb0cd992ca56097baba0R9 (creating a tag and pushing it).

The GitHub action will build the sdist and wheel and upload them to PyPI.

**Comment by rabernat** [comment]
Awesome! I'll merge and release now.

**Comment by rabernat** [comment]
Release failed! 😭 
https://github.com/pangeo-data/rechunker/runs/1248918479?check_suite_focus=true

Seems to be a credentials problem. Any thoughts?

**Comment by TomAugspurger** [comment]
I wonder if it's the case? PYPI_TOKEN vs. pypi_token? Let me try fixing that quick.

**Comment by TomAugspurger** [comment]
https://github.com/pangeo-data/rechunker/pull/56.

If you want to try again, you can try pushing a different tag. That would mean we just don't have a v0.3.0 on PyPI.

Or you (or I) can build the dists locally and upload them.

**Comment by rabernat** [comment]
I have no problem with just going to 0.3.1. Would you give it a try?

**Comment by TomAugspurger** [comment]
Sure, pushing now.

**Comment by TomAugspurger** [comment]
Hmm that failed too...

I'll build these locally and push manually, and then test on another repo.

**Comment by TomAugspurger** [comment]
OK, 0.3.1 is up on PyPI.

**Comment by TomAugspurger** [comment]
I think 63a6509023c9e64eed2788d0d6b70124ccfbdcb5 fixed this. Apparently the username really is supposed to be `__token__` when you're using PyPI tokens.

**Comment by rabernat** [comment]
> Apparently the username really is supposed to be `__token__` when you're using PyPI tokens.

Good to know! Thanks for seeing this through!

**Pull request merged**
