### PR TITLE
Fuse graph in case where read and write chunks are the same.

### PR DESCRIPTION
**Pull request by tomwhite**

### CODE REVIEW

**Comment by rabernat** [comment]
Good catch--thanks @tomwhite! Any thoughts on how we could be testing for this sort of thing?  Should we examine the graph in the tests?

**Comment by TomAugspurger** [comment]
Asserting that the length of the task graph is less than the un-fused length is probably best (just hardcode the old length I think)

**Comment by tomwhite** [comment]
Added a test to do this. Note that it compares actual tasks, not just the length of the graph since that doesn't change.

**Comment by rabernat** [comment]
Fantastic! You will have to run black on your branch--that's why the lint test failed.  Sorry for the inconvenience. This package is brand new and we're still sorting on the dev workflow.

**Pull request merged**
